apiVersion: v1
kind: Service
metadata:
  name: services

spec:
  type: NodePort
  selector:
    app: row
  ports:
    - port: 8080        #service
      targetPort: 80    #pod/container
      nodePort: 30005   